(function (global) {
    'use strict';
    global.CoSAFECatalog = {
        'proteccion-civil': { group: 'principal', code: 'EHSS 01', title: 'Protección Civil y trámites', description: 'Prevención, respuesta ante emergencias y requisitos de operación.', services: ['Programa Interno de Protección Civil', 'Simulacros', 'Organización y revisión de brigadas', 'Vistos buenos', 'Asesoría de cumplimiento', 'Elaboración y gestión de dictámenes', 'Dictamen estructural', 'Dictamen eléctrico', 'Licencia de funcionamiento', 'Certificado o trámite de uso de suelo', 'Manifiesto de propiedad', 'Trámite municipal', 'Trámite estatal', 'Seguimiento ante autoridad', 'Señalización de seguridad'] },
        'seguridad-industrial': { group: 'principal', code: 'EHSS 02', title: 'Seguridad Industrial y Estudios Técnicos', description: 'Evaluaciones técnicas, cumplimiento, expedientes y acciones correctivas.', services: ['Evaluación técnica industrial', 'Diagnóstico general de seguridad', 'Evaluación de instalaciones, áreas o procesos', 'Estudio técnico conforme a requerimientos aplicables', 'Revisión de cumplimiento STPS', 'Dictamen técnico', 'Dictamen estructural', 'Dictamen eléctrico', 'Diagnóstico de necesidades', 'Atención de observaciones', 'Integración de expediente para auditoría o revisión', 'Seguimiento de acciones correctivas'] },
        'ambiental': { group: 'principal', code: 'EHSS 03', title: 'Estudios y Cumplimiento Ambiental', description: 'Evaluación, gestión documental, regularización y seguimiento ambiental.', services: ['Diagnóstico de cumplimiento ambiental', 'Evaluación documental', 'Estudio ambiental', 'Trámite ambiental', 'Integración documental', 'Seguimiento ante autoridad', 'Regularización ambiental', 'Atención de observaciones', 'Gestión de vigencias y calendario ambiental', 'Desarrollo urbano', 'Medio ambiente', 'Otro estudio o trámite ambiental'] },
        'salud': { group: 'principal', code: 'EHSS 04', title: 'Salud Ocupacional y Servicios Médicos en Planta', description: 'Servicios médicos, preventivos y de seguimiento para trabajadores.', services: ['Servicio médico industrial en planta', 'Servicio de enfermería industrial en planta', 'Atención médica laboral y primer contacto', 'Seguimiento de trabajadores', 'Exámenes médicos ocupacionales', 'Exámenes periódicos', 'Evaluación ocupacional', 'Control de resultados', 'Programas de salud ocupacional', 'Administración y seguimiento de incapacidades', 'Campañas y promoción de la salud', 'Paramédicos', 'Psicología', 'Nutrición', 'Vacunación para viajeros internacionales', 'Atención de emergencias', 'Canalización o traslado hospitalario'] },
        'epp': { group: 'principal', code: 'EHSS 05', title: 'Equipo de Protección Personal', description: 'Selección, venta y suministro según actividad, riesgo y consumo.', services: ['Venta de EPP', 'Suministro empresarial', 'Asesoría para selección de EPP', 'Identificación de necesidades', 'Recomendación por riesgo o actividad', 'Suministro recurrente'] },
        'extintores': { group: 'principal', code: 'EHSS 06', title: 'Extintores y Protección Contra Incendios', description: 'Asesoría, suministro, servicio periódico y elementos relacionados.', services: ['Asesoría e identificación de necesidades', 'Selección de equipo', 'Venta y suministro', 'Recarga', 'Reacondicionamiento', 'Recarga periódica', 'Mantenimiento', 'Inspección periódica', 'Revisión preventiva', 'Verificación y seguimiento', 'Señalización', 'Soportes y gabinetes', 'Asesoría de ubicación', 'Programa recurrente de extintores'] },
        'tramites': { group: 'transversal', code: 'TRANSVERSAL', title: 'Trámites municipales y estatales', description: 'Acceso directo para clasificar requisitos según autoridad y ubicación.', services: ['Licencia de funcionamiento', 'Uso de suelo', 'Visto bueno', 'Manifiesto de propiedad', 'Dictamen relacionado', 'Trámite municipal', 'Trámite estatal', 'Integración de expediente', 'Atención de observaciones', 'Seguimiento ante autoridad'] },
        'capacitacion': { group: 'complementario', code: 'COMPLEMENTARIO 01', title: 'Cursos y Capacitaciones', description: 'Formación por evento, grupo o programa anual.', services: ['Curso en instalaciones del cliente', 'Curso para grupo cerrado', 'Curso abierto', 'Programa anual de capacitación', 'Capacitación para brigadas', 'Capacitación de seguridad, salud o medio ambiente', 'Evidencia, evaluación y constancias'] },
        'intendencia': { group: 'complementario', code: 'COMPLEMENTARIO 02', title: 'Personal de Intendencia y Suministros', description: 'Cobertura operativa por turno, periodo o contrato recurrente.', services: ['Personal de intendencia por turno', 'Cobertura temporal', 'Servicio recurrente de intendencia', 'Suministros de limpieza', 'Servicio integral de personal más suministros'] }
    };
})(window);
